In [1]:
import pandas as pd
import csv

In [2]:
with open('../data/tickers.csv') as f:
    reader = csv.reader(f)
    tickers = {}
    next(reader)
    for line in reader:
        tickers[line[0]] = line[-1]

In [3]:
tickers = pd.read_csv('../data/tickers.csv')[['gvkey', 'co_tic']]
tickers_list = tickers['co_tic'].unique()

In [4]:
ratios = pd.read_csv('../data/ratios-history-full.csv')

In [5]:
ratios

,gvkey,adate,qdate,public_date,bm,pe_op_dil,pcf,gpm,roa,roe,aftret_invcapx,capital_ratio,quick_ratio,curr_ratio,ptb,PEG_1yrforward
0,1004,05/31/2000,11/30/2000,01/31/2001,1.439,19.727,15.888,0.180,0.092,0.053,0.077,0.346,1.031,2.955,1.017,-0.499
1,1013,10/31/2000,10/31/2000,01/31/2001,0.177,52.009,51.357,0.523,0.237,0.417,0.692,0.006,2.079,2.546,3.904,0.332
2,1034,12/31/1999,09/30/2000,01/31/2001,0.343,24.832,43.546,0.540,0.153,0.119,0.094,0.541,1.313,2.434,1.334,1.064
3,1038,03/31/2000,09/30/2000,01/31/2001,0.698,-1.867,2.088,0.125,0.075,-0.742,0.022,0.935,0.760,0.760,3.795,-0.082
4,1045,12/31/1999,09/30/2000,01/31/2001,1.879,6.032,2.079,0.143,0.112,0.111,0.100,0.446,0.652,0.760,0.636,0.726
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
965366,298036,12/31/2018,09/30/2019,12/31/2019,0.996,-21.000,50.032,0.214,0.068,-0.075,0.006,0.447,1.203,1.203,1.238,NaN
965367,315318,12/31/2018,09/30/2019,12/31/2019,0.880,-311.500,-66.204,0.513,0.056,-0.004,0.025,0.535,2.008,2.363,1.304,NaN
965368,328795,12/31/2018,09/30/2019,12/31/2019,1.107,17.964,9.844,0.242,0.115,0.071,0.070,0.074,1.611,2.847,1.179,NaN
965369,331856,NaN,09/30/2019,12/31/2019,0.601,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.621,NaN
965370,332115,NaN,09/30/2019,12/31/2019,0.577,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.522,NaN

In [38]:
ratios_with_tickers = ratios.merge(tickers, on='gvkey').drop_duplicates()
ratios_with_tickers.drop(['gvkey', 'adate', 'qdate'], inplace=True, axis=1)

In [40]:
ratios_by_tickers = ratios_with_tickers.set_index(['public_date', 'co_tic'])
ratios_by_tickers = ratios_by_tickers.unstack(level=-1)
ratios_by_tickers = ratios_by_tickers.swaplevel(0, 1, axis=1)
ratios_by_tickers = ratios_by_tickers.sort_index(axis=1, level=0)
ratios_by_tickers = ratios_by_tickers.sort_index(axis=0)
ratios_by_tickers

co_tic                 NaN                                                 \
            PEG_1yrforward aftret_invcapx     bm capital_ratio curr_ratio
public_date
01/31/2001           0.999          0.000  0.079         0.080      1.450
01/31/2002          -2.701          0.000  0.076         0.090      1.288
01/31/2003           1.397          0.000  0.063         0.101      1.041
01/31/2004           1.341          0.410  0.064         0.087      1.010
01/31/2005           1.291          0.494  0.068         0.076      1.029
...                    ...            ...    ...           ...        ...
12/31/2015             NaN            NaN    NaN           NaN        NaN
12/31/2016             NaN            NaN    NaN           NaN        NaN
12/31/2017             NaN            NaN    NaN           NaN        NaN
12/31/2018             NaN            NaN    NaN           NaN        NaN
12/31/2019             NaN          0.145    NaN         1.064      0.758

co_tic                                                    ...   ZUMZ  \
               gpm     pcf pe_op_dil     ptb quick_ratio  ...     bm
public_date                                               ...
01/31/2001   0.213  17.655    31.860  11.158       1.374  ...    NaN
01/31/2002   0.186  18.070    41.652  14.987       1.240  ...    NaN
01/31/2003   0.184  17.919    32.243  13.239       1.004  ...    NaN
01/31/2004   0.189  22.799    35.200  14.541       0.964  ...    NaN
01/31/2005   0.189  22.807    34.512  17.649       0.986  ...    NaN
...            ...     ...       ...     ...         ...  ...    ...
12/31/2015     NaN     NaN       NaN     NaN         NaN  ...  0.647
12/31/2016     NaN     NaN       NaN     NaN         NaN  ...  0.522
12/31/2017     NaN     NaN       NaN     NaN         NaN  ...  0.733
12/31/2018     NaN     NaN       NaN     NaN         NaN  ...  0.621
12/31/2019   0.351   1.493     8.262     NaN       0.685  ...  0.518

co_tic                                                                \
            capital_ratio curr_ratio    gpm     pcf pe_op_dil    ptb
public_date
01/31/2001            NaN        NaN    NaN     NaN       NaN    NaN
01/31/2002            NaN        NaN    NaN     NaN       NaN    NaN
01/31/2003            NaN        NaN    NaN     NaN       NaN    NaN
01/31/2004            NaN        NaN    NaN     NaN       NaN    NaN
01/31/2005            NaN        NaN    NaN     NaN       NaN    NaN
...                   ...        ...    ...     ...       ...    ...
12/31/2015           0.00      2.893  0.381   7.208    11.118  1.337
12/31/2016           0.00      2.253  0.362  10.438    26.012  1.880
12/31/2017           0.00      2.370  0.358   9.013    20.417  1.610
12/31/2018           0.00      2.586  0.371   7.117    13.693  1.327
12/31/2019           0.35      2.382  0.373  11.478    14.888  2.088

co_tic
            quick_ratio    roa    roe
public_date
01/31/2001          NaN    NaN    NaN
01/31/2002          NaN    NaN    NaN
01/31/2003          NaN    NaN    NaN
01/31/2004          NaN    NaN    NaN
01/31/2005          NaN    NaN    NaN
...                 ...    ...    ...
12/31/2015        1.617  0.192  0.095
12/31/2016        0.930  0.147  0.071
12/31/2017        1.059  0.149  0.082
12/31/2018        1.339  0.175  0.102
12/31/2019        1.375  0.142  0.150

[228 rows x 34272 columns]

In [ ]:
ratios_by_tickers.to_csv('../data/wrds_ratios_formatted.csv')