In [1]:
import pandas as pd
import csv

In [2]:
with open('../data/tickers.csv') as f:
    reader = csv.reader(f)
    tickers = {}
    next(reader)
    for line in reader:
        tickers[line[0]] = line[-1]

In [3]:
tickers = pd.read_csv('../data/tickers.csv')[['gvkey', 'co_tic']]
tickers_list = tickers['co_tic'].unique()

In [4]:
ratios = pd.read_csv('../data/ratios-history-full.csv')

In [5]:
ratios

,gvkey,adate,qdate,public_date,bm,pe_op_dil,pcf,gpm,roa,roe,aftret_invcapx,capital_ratio,quick_ratio,curr_ratio,ptb,PEG_1yrforward
0,1004,05/31/2000,11/30/2000,01/31/2001,1.439,19.727,15.888,0.180,0.092,0.053,0.077,0.346,1.031,2.955,1.017,-0.499
1,1013,10/31/2000,10/31/2000,01/31/2001,0.177,52.009,51.357,0.523,0.237,0.417,0.692,0.006,2.079,2.546,3.904,0.332
2,1034,12/31/1999,09/30/2000,01/31/2001,0.343,24.832,43.546,0.540,0.153,0.119,0.094,0.541,1.313,2.434,1.334,1.064
3,1038,03/31/2000,09/30/2000,01/31/2001,0.698,-1.867,2.088,0.125,0.075,-0.742,0.022,0.935,0.760,0.760,3.795,-0.082
4,1045,12/31/1999,09/30/2000,01/31/2001,1.879,6.032,2.079,0.143,0.112,0.111,0.100,0.446,0.652,0.760,0.636,0.726
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
965366,298036,12/31/2018,09/30/2019,12/31/2019,0.996,-21.000,50.032,0.214,0.068,-0.075,0.006,0.447,1.203,1.203,1.238,NaN
965367,315318,12/31/2018,09/30/2019,12/31/2019,0.880,-311.500,-66.204,0.513,0.056,-0.004,0.025,0.535,2.008,2.363,1.304,NaN
965368,328795,12/31/2018,09/30/2019,12/31/2019,1.107,17.964,9.844,0.242,0.115,0.071,0.070,0.074,1.611,2.847,1.179,NaN
965369,331856,NaN,09/30/2019,12/31/2019,0.601,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.621,NaN
965370,332115,NaN,09/30/2019,12/31/2019,0.577,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.522,NaN

In [6]:
ratios_with_tickers = ratios.merge(tickers, on='gvkey').drop_duplicates()
ratios_with_tickers.drop(['gvkey', 'adate', 'qdate'], inplace=True, axis=1)

In [7]:
ratios_with_tickers

,public_date,bm,pe_op_dil,pcf,gpm,roa,roe,aftret_invcapx,capital_ratio,quick_ratio,curr_ratio,ptb,PEG_1yrforward,co_tic
0,01/31/2001,1.439,19.727,15.888,0.180,0.092,0.053,0.077,0.346,1.031,2.955,1.017,-0.499,AIR
20,02/28/2001,1.439,17.662,14.225,0.180,0.092,0.053,0.077,0.346,1.031,2.955,0.911,-0.464,AIR
40,03/31/2001,1.439,16.571,13.347,0.180,0.092,0.053,0.077,0.346,1.031,2.955,0.854,-0.427,AIR
60,04/30/2001,1.107,19.702,48.015,0.185,0.081,0.038,0.066,0.346,0.992,2.993,0.746,-0.415,AIR
80,05/31/2001,1.107,24.561,59.858,0.185,0.081,0.038,0.066,0.346,0.992,2.993,0.930,-0.518,AIR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10517954,09/30/2019,1.234,-27.723,15.521,0.436,0.017,-0.086,-0.074,0.092,1.062,1.648,0.768,NaN,CTVA
10517969,10/31/2019,1.234,-26.119,14.613,0.436,0.017,-0.086,-0.074,0.092,1.062,1.648,0.723,NaN,CTVA
10517984,11/30/2019,1.257,32.123,17.607,0.437,0.020,-0.021,-0.016,0.067,1.064,1.622,0.739,NaN,CTVA
10517999,12/31/2019,1.257,36.494,20.002,0.437,0.020,-0.021,-0.016,0.067,1.064,1.622,0.840,NaN,CTVA
10518014,12/31/2019,0.077,54.213,66.999,0.139,0.094,0.159,0.049,0.722,0.769,0.769,12.951,NaN,PNTG

In [22]:
stacked_by_tickers = ratios_with_tickers.set_index(['public_date', 'co_tic'])

In [27]:
stacked_by_tickers.unstack().swaplevel(0,1, axis=1)['ABBV']

,bm,pe_op_dil,pcf,gpm,roa,roe,aftret_invcapx,capital_ratio,quick_ratio,curr_ratio,ptb,PEG_1yrforward
public_date,,,,,,,,,,,,
01/31/2001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
01/31/2002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
01/31/2003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
01/31/2004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
01/31/2005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
12/31/2015,0.122,17.631,19.392,0.850,0.250,0.565,0.160,0.855,1.427,1.559,8.918,1.205
12/31/2016,0.123,14.200,13.636,0.827,0.195,0.566,0.165,0.866,1.481,1.653,8.081,1.370
12/31/2017,0.090,20.232,17.314,0.826,0.179,0.550,0.162,0.863,1.398,1.540,12.030,1.529
12/31/2018,0.049,14.360,10.989,0.816,0.206,0.864,0.234,0.982,1.014,1.116,18.278,0.456
12/31/2019,NaN,11.208,9.741,0.833,0.260,NaN,0.163,1.322,0.907,1.016,NaN,3.150

In [ ]:
ratios_by_tickers = ratios_with_tickers.set_index(['public_date', 'co_tic'])
ratios_by_tickers = ratios_by_tickers.unstack(level=-1)
ratios_by_tickers = ratios_by_tickers.swaplevel(0, 1, axis=1)
ratios_by_tickers = ratios_by_tickers.sort_index(axis=1, level=0)
ratios_by_tickers = ratios_by_tickers.sort_index(axis=0)
ratios_by_tickers.set_index('public_date')
ratios_by_tickers

In [ ]:
ratios_by_tickers.to_csv('../data/wrds_ratios_formatted.csv')